### ISSUE TITLE
Support assume role with EKS

### ISSUE THREAD

**Issue by webframp** [darkbitio/mkit#4]
Similar to auth provider issues in #2 I think, but maybe slightly different. Close if you feel appropriate.

This line: https://github.com/darkbitio/mkit/blob/master/support/eks.sh#L30 could support the `--role-arn` argument for the `aws eks update-kubeconfig.

Currently hacking my way around in the container to still experiment with the inspec profiles, but would simplify things for me if this was supported.

**Comment by chiefy** [comment]
Getting AWS token issues even when running bare `run-k8s` ?

```
🚽 make run-k8s
Running in darkbitio/mkit:latest: /home/node/audit/k8s.sh
Generating results...could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Traceback (most recent call last):
	21: from /home/node/.gem/ruby/2.6.0/bin/cinc-auditor:23:in `<main>'
	20: from /home/node/.gem/ruby/2.6.0/bin/cinc-auditor:23:in `load'
	19: from /home/node/.gem/ruby/2.6.0/gems/cinc-auditor-bin-4.18.51/bin/cinc-auditor:12:in `<top (required)>'
	18: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in `start'
	17: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	16: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	15: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	14: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	13: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `exec'
	12: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `new'
	11: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:78:in `initialize'
	10: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:86:in `configure_transport'
	 9: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/backend.rb:53:in `create'
	 8: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/transport.rb:9:in `connection'
	 7: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/transport.rb:9:in `new'
	 6: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/connection.rb:13:in `initialize'
	 5: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/connection.rb:36:in `parse_kubeconfig'
	 4: from /home/node/.gem/ruby/2.6.0/gems/k8s-ruby-0.10.5/lib/k8s/client.rb:40:in `config'
	 3: from /home/node/.gem/ruby/2.6.0/gems/k8s-ruby-0.10.5/lib/k8s/transport.rb:81:in `config'
	 2: from /home/node/.gem/ruby/2.6.0/gems/k8s-ruby-0.10.5/lib/k8s/transport.rb:120:in `token_from_exec'
	 1: from /usr/local/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)
Traceback (most recent call last):
./inspec-results-parser.rb:92:in `<main>': undefined method `dig' for nil:NilClass (NoMethodError)
```

**Comment by bgeesaman** [comment]
@webframp Thanks for bringing up your use case!  I'd be very open to a PR to add this as an optional argument to pass through.

If that's not something you're up for, try this. We typically use `aws-vault` to handle fetching creds and assuming a role, so our `.aws/config` looks like this:

```
[profile myprofile]
mfa_serial=arn:aws:iam::1234567890:mfa/myuser
role_arn=arn:aws:iam::1234567890:role/myRole
credential_process=aws-vault exec myprofile --json --prompt=osascript
```

and we invoke the run like this so that the temp/assumed role creds grabbed by aws-vault pass in as ENV vars to the container:
```
$ aws-vault exec myprofile -- make run-eks awsregion=us-east-1 clustername=eks1
```

**Comment by bgeesaman** [comment]
Closing this for now, but we'd take a PR on this anytime.  Thanks!
