### ISSUE TITLE
run Error

### ISSUE THREAD

**Issue by itsecforu** [darkbitio/mkit#9]
Hey!

I try to start make run-k8s on master node of baremetal k8s.

I get this error^ 

```
make run-k8s
Running in darkbitio/mkit:latest: /home/node/audit/k8s.sh
Generating results...Traceback (most recent call last):
        18: from /home/node/.gem/ruby/2.6.0/bin/cinc-auditor:23:in `<main>'
        17: from /home/node/.gem/ruby/2.6.0/bin/cinc-auditor:23:in `load'
        16: from /home/node/.gem/ruby/2.6.0/gems/cinc-auditor-bin-4.18.51/bin/cinc-auditor:12:in `<top (required)>'
        15: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in `start'
        14: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        13: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        12: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        11: from /home/node/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        10: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `exec'
         9: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:284:in `new'
         8: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:78:in `initialize'
         7: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/runner.rb:86:in `configure_transport'
         6: from /home/node/.gem/ruby/2.6.0/gems/inspec-4.18.51/lib/inspec/backend.rb:53:in `create'
         5: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/transport.rb:9:in `connection'
         4: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/transport.rb:9:in `new'
         3: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/connection.rb:13:in `initialize'
         2: from /home/node/.gem/ruby/2.6.0/gems/train-kubernetes-0.1.5/lib/train-kubernetes/connection.rb:36:in `parse_kubeconfig'
         1: from /home/node/.gem/ruby/2.6.0/gems/k8s-ruby-0.10.5/lib/k8s/config.rb:114:in `load_file'
/home/node/.gem/ruby/2.6.0/gems/k8s-ruby-0.10.5/lib/k8s/config.rb:114:in `read': Permission denied @ rb_sysopen - /home/node/.kube/config (Errno::EACCES)
Traceback (most recent call last):
./inspec-results-parser.rb:92:in `<main>': undefined method `dig' for nil:NilClass (NoMethodError)
```

**Comment by bgeesaman** [comment]
Hi @itsecforu .  When Inspec throws an error, it mixes in the error into the output and that is not valid json, so the results parser throws that error trying to "dig" into something that isn't a valid hash.  To address the issue, we have to figure out what is causing Inspec to throw an error.  Knowing that you are on a master node, the root cause is likely that the KUBECONFIG isn't being mounted in from the correct location, and Inspec is probably throwing an error saying it's unable to connect to the cluster API server.

Take a look at https://github.com/darkbitio/mkit/blob/master/Makefile#L64
```
  -v $(K8SKUBECONFIG):/${HOMEDIR}/.kube/config:ro
```
This line mounts in the local KUBECONFIG to `/home/node/.kube/config` inside the MKIT container.

Try modifying it like so:
```
  -v /etc/kubernetes/admin.conf:/${HOMEDIR}/.kube/config:ro
```
Change that path if that's not correct.  Re-run and see if that helps.

**Comment by itsecforu** [comment]
Hey! thx for feedback
The problem:

```
make run-k8s
Makefile:65: *** target pattern contains no `%'.  Stop.

```
My changes Makefile:
![1](https://user-images.githubusercontent.com/38696837/93093886-e29bf900-f6a9-11ea-9f7d-77aa7b84b7d2.png)

**Comment by itsecforu** [comment]
I temporarily made permissions to the config file.

Now i got other error:

```
make run-k8s
Running in darkbitio/mkit:latest: /home/node/audit/k8s.sh
Generating results...Profile git dependency failed for https://github.com/bgeesaman/inspec-k8s - error running 'git ls-remote "https://g                             ithub.com/bgeesaman/inspec-k8s" "0.1.3*"': fatal: unable to access 'https://github.com/bgeesaman/inspec-k8s/': Failed to connect to gith                             ub.com port 443: Connection refused
Traceback (most recent call last):
./inspec-results-parser.rb:92:in `<main>': undefined method `dig' for nil:NilClass (NoMethodError)

```
